### ISSUE TITLE
Can't install termstyle

### ISSUE THREAD

**Issue by kengruven** [gfxmonk/termstyle#8]
When trying to install via pip, it tries to fetch "http://gfxmonk.net/dist/0install/python-termstyle.xml", whose server doesn't seem to be responding.

**Comment by noirbizarre** [comment]
+1
You should upload them on PyPI instead of hosting them yourself.

**Comment by gfxmonk** [comment]
I'm afraid I haven't used `pip` in years, so maybe I'm missing something. I just set up a virtualenv, and it installs fine (but my server is working for me, and it's possibly cached anyway).

The [pypi page](https://pypi.python.org/pypi/python-termstyle) shows archives for the latest version of termstyle were uploaded in 2013 though, so I don't know why it wouldn't be working for you.

For reasons which escape my memory, note that you need `python-termstyle`, not `termstyle`. It is a silly package name, I know. Maybe that's your issue?

**Comment by noirbizarre** [comment]
The main issue is https://github.com/gfxmonk/termstyle/blob/master/setup.py#L16
It says "Do not use PyPI for download".

The name defined here: https://github.com/gfxmonk/termstyle/blob/master/setup.py#L15 (in which, I agree, `python-` is useless :)) is not an issue.

**Comment by gfxmonk** [comment]
Ahh ok. I've removed the download location, and fixed it up on pypi as well I believe - let me know if you still have trouble. Funny, I've also seen people reporting (on other packages) that `pip` would _only_ download files from pypi, and would no longer respect external links. Can't win...

**Comment by noirbizarre** [comment]
Thanks for your reactivity !

About external links, I think this is about the `dependency_links` attribute.
